### ISSUE TITLE
Generic boards fqdn unknown

### ISSUE THREAD

**Issue by nilsonLazarin** [chon-group/chonIDE#12]
When using generic boards (ttyUSB0) the _arduino-cli_ informs Unknown, in this case, the _compile_ and _deploy_  buttons assuming that is an Arduino UNO.
In case there is an Arduino MEGA in the ttyUSB0, it is not possible to deploy the code.  

![Captura de tela de 2023-05-17 20-11-53](https://github.com/chon-group/chonIDE/assets/32855001/05878e24-388d-4946-b7ed-8b5b1b329860)

**Comment by gabrielramosalv** [comment]
![image](https://github.com/chon-group/chonIDE/assets/77932106/b1fd3b08-3675-4d56-ae18-8752e9dc9551)
![image](https://github.com/chon-group/chonIDE/assets/77932106/80241cf1-b6f9-4fce-8923-f9494d65c1be)
