### ISSUE TITLE
Connect in network - never end

### ISSUE THREAD

**Issue by nilsonLazarin** [chon-group/chonIDE#13]
When I choose the wireless network, the ChonBot connect and reboot, but the chonIDE standalone is blocked in this page.

I need to clean the cache of the browser to solve this bug.

![Captura de tela de 2023-08-27 19-33-06](https://github.com/chon-group/chonIDE/assets/32855001/24134bf3-033c-462b-8d13-3ed4ace71333)

**Comment by nilsonLazarin** [comment]
### How solve manually

When ChonIDE login is in loop is need to delete the cookies. Below are some prints to solve it manually.

![erro](https://github.com/chon-group/chonIDE/assets/32855001/3a608f6f-4b7d-4f58-aeae-b1e85bb718d4)


![apagar1](https://github.com/chon-group/chonIDE/assets/32855001/e831a917-8ef5-4224-a938-8d5ef0f71518)

![apagar2](https://github.com/chon-group/chonIDE/assets/32855001/81f5a381-6c97-4fab-8f5b-a13bd25b4acc)

**Comment by gabrielramosalv** [comment]
![image](https://github.com/chon-group/chonIDE/assets/77932106/f575ce52-8f17-4119-ab8d-37d89ede94fb)
