### ISSUE TITLE
Bug in the Start MAS message

### ISSUE THREAD

**Issue by nilsonLazarin** [chon-group/chonIDE#3]
The JSON message when starting the Multiagent System is not being interpreted.

![Captura de tela de 2023-04-27 03-29-04](https://user-images.githubusercontent.com/32855001/234778310-75ed5dcf-7663-4c5b-8b68-b238386e7d97.png)

**Comment by gabrielramosalv** [comment]
![image](https://github.com/chon-group/chonIDE/assets/77932106/91f84f67-20be-4343-8502-d79ada328d57)
