### ISSUE TITLE
Upload & Download Projects

### ISSUE THREAD

**Issue by profpantoja** [chon-group/chonIDE#9]
It needs the upload and download functionalities.
It will download saved projects and upload projects to chonIDE.

**Comment by nilsonLazarin** [comment]
I think that in the Projects List Page, new options can be to solve this necessity.

To download a project, should need, a new option in the (...) button of project. 
![WhatsApp Image 2023-09-13 at 12 38 52](https://github.com/chon-group/chonIDE/assets/32855001/62111d4d-ae85-48da-9b9e-c14209d74741)

This button could download the file project.json in the ChonIDE Project Folder
![WhatsApp Image 2023-09-13 at 12 43 41](https://github.com/chon-group/chonIDE/assets/32855001/dc5dadaa-b578-48b2-b368-c9d1f0e7c2d0)

**Comment by nilsonLazarin** [comment]
In the same way, to import a ChonIDE Project.

![WhatsApp Image 2023-09-13 at 12 51 22](https://github.com/chon-group/chonIDE/assets/32855001/c15e6ac6-58f8-49d1-9dc9-9ebcc52b21b4)
